paths:
  /Usuarios:
    post:
      tags:
        - Usuario
      summary: Create a new instance of the model and persist it into the data source.
      operationId: Usuario.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Usuario'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Usuario'
      deprecated: false
    put:
      tags:
        - Usuario
      summary: Patch an existing model instance or insert a new one into the data source.
      operationId: Usuario.upsert__put_Usuarios
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Usuario'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Usuario'
      deprecated: false
    patch:
      tags:
        - Usuario
      summary: Patch an existing model instance or insert a new one into the data source.
      operationId: Usuario.upsert__patch_Usuarios
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Usuario'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Usuario'
      deprecated: false
    get:
      tags:
        - Usuario
      summary: Find all instances of the model matched by filter from the data source.
      operationId: Usuario.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Usuario'
      deprecated: false
  /Usuarios/replaceOrCreate:
    post:
      tags:
        - Usuario
      summary: Replace an existing model instance or insert a new one into the data source.
      operationId: Usuario.replaceOrCreate
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Usuario'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Usuario'
      deprecated: false
  /Usuarios/upsertWithWhere:
    post:
      tags:
        - Usuario
      summary: Update an existing model instance or insert a new one into the data source based on the where criteria.
      operationId: Usuario.upsertWithWhere
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Usuario'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Usuario'
      deprecated: false
  '/Usuarios/{id}/exists':
    get:
      tags:
        - Usuario
      summary: Check whether a model instance exists in the data source.
      operationId: 'Usuario.exists__get_Usuarios_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/Usuarios/{id}':
    head:
      tags:
        - Usuario
      summary: Check whether a model instance exists in the data source.
      operationId: 'Usuario.exists__head_Usuarios_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - Usuario
      summary: 'Find a model instance by {{id}} from the data source.'
      operationId: Usuario.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: 'Filter defining fields and include - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Usuario'
      deprecated: false
    delete:
      tags:
        - Usuario
      summary: 'Delete a model instance by {{id}} from the data source.'
      operationId: Usuario.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    put:
      tags:
        - Usuario
      summary: Patch attributes for a model instance and persist it into the data source.
      operationId: 'Usuario.prototype.updateAttributes__put_Usuarios_{id}'
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Usuario'
        - name: id
          in: path
          description: Usuario id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Usuario'
      deprecated: false
    patch:
      tags:
        - Usuario
      summary: Patch attributes for a model instance and persist it into the data source.
      operationId: 'Usuario.prototype.updateAttributes__patch_Usuarios_{id}'
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Usuario'
        - name: id
          in: path
          description: Usuario id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Usuario'
      deprecated: false
  '/Usuarios/{id}/replace':
    post:
      tags:
        - Usuario
      summary: Replace attributes for a model instance and persist it into the data source.
      operationId: Usuario.replaceById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Usuario'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Usuario'
      deprecated: false
  /Usuarios/findOne:
    get:
      tags:
        - Usuario
      summary: Find first instance of the model matched by filter from the data source.
      operationId: Usuario.findOne
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Usuario'
      deprecated: false
  /Usuarios/update:
    post:
      tags:
        - Usuario
      summary: 'Update instances of the model matched by {{where}} from the data source.'
      operationId: Usuario.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Usuario'
      responses:
        '200':
          description: Request was successful
          schema:
            description: Information related to the outcome of the operation
            type: object
            properties:
              count:
                description: The number of instances updated
                type: number
                format: double
      deprecated: false
  /Usuarios/count:
    get:
      tags:
        - Usuario
      summary: Count instances of the model matched by where from the data source.
      operationId: Usuario.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
definitions:
  Usuario:
    properties:
      id:
        type: number
        format: double
      correo:
        maxLength: 30
        type: string
      contrasena:
        maxLength: 15
        type: string
      rut:
        maxLength: 11
        type: string
      numerotelefono:
        type: number
        format: double
      direccion:
        maxLength: 80
        type: string
      fecha:
        type: string
        format: date-time
      baneado:
        type: number
        format: double
      nombre:
        maxLength: 25
        type: string
      idtipousuario:
        type: number
        format: double
    required:
      - id
      - correo
      - contrasena
      - rut
      - numerotelefono
      - direccion
      - fecha
      - baneado
      - nombre
      - idtipousuario
    additionalProperties: false
  x-any:
    properties: {}
basePath: /api
swagger: '2.0'
info:
  x-ibm-name: aljosserver
  version: 1.0.0
  title: AljosServer
schemes:
  - http
host: $(catalog.host)
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - clientIdHeader: []
    clientSecretHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:4001'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
